apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cybernetics-agent
  namespace: cybernetics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: cybernetics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cybernetics-agent
                port:
                  number: 8080
